#!/usr/bin/env python3
"""
Load Cell Calibration Helper
Use this to determine scale factors for converting raw values to weight
"""

import time
import sys
from ads1256_load_cells import ADS1256, read_avg_raw

# Same configuration as main script
CS_PIN = 22
DRDY_PIN = 17
CHANNEL_1 = 0
CHANNEL_2 = 1
DRATE_100 = 0x82
GAIN_1 = 0x00

def get_stable_reading(ads, channel, samples=50, timeout=10):
    """Get a stable reading from a channel"""
    print(f"  Reading from channel {channel}... ", end='', flush=True)
    
    readings = []
    start_time = time.time()
    
    while len(readings) < samples:
        if time.time() - start_time > timeout:
            print("TIMEOUT")
            return None
        
        val = ads.read_channel(channel)
        if val is not None:
            readings.append(val)
            if len(readings) % 10 == 0:
                print(f"{len(readings)}", end=' ', flush=True)
        time.sleep(0.02)
    
    avg = sum(readings) / len(readings)
    std_dev = (sum((x - avg) ** 2 for x in readings) / len(readings)) ** 0.5
    print(f"\n  Average: {avg:.2f}, Std Dev: {std_dev:.2f}")
    return avg

def calibrate_channel(ads, channel, channel_name):
    """Calibrate a single load cell channel"""
    print(f"\n{'='*60}")
    print(f"Calibrating {channel_name} (Channel {channel})")
    print('='*60)
    
    # Step 1: Zero reading
    input(f"\n1. Remove ALL weight from {channel_name}. Press Enter when ready...")
    zero_value = get_stable_reading(ads, channel)
    if zero_value is None:
        print("Failed to get zero reading!")
        return None, None
    
    # Step 2: Known weight reading
    print(f"\n2. Place a KNOWN WEIGHT on {channel_name}.")
    weight_input = input("   Enter the weight in kg (or type 'skip'): ")
    
    if weight_input.lower() == 'skip':
        return zero_value, None
    
    try:
        known_weight = float(weight_input)
    except ValueError:
        print("Invalid weight entered!")
        return zero_value, None
    
    input("   Press Enter when weight is stable on the load cell...")
    loaded_value = get_stable_reading(ads, channel)
    if loaded_value is None:
        print("Failed to get loaded reading!")
        return zero_value, None
    
    # Calculate scale factor
    delta = loaded_value - zero_value
    if abs(delta) < 10:
        print(f"\n⚠ WARNING: Very small change detected ({delta:.2f})")
        print("   - Check load cell is connected properly")
        print("   - Adjust AD620 gain potentiometer")
        print("   - Try a heavier known weight")
        return zero_value, None
    
    scale_factor = known_weight / delta
    
    print(f"\n{'='*60}")
    print(f"Calibration Results for {channel_name}:")
    print(f"  Zero Value:    {zero_value:.2f}")
    print(f"  Loaded Value:  {loaded_value:.2f}")
    print(f"  Delta:         {delta:.2f}")
    print(f"  Known Weight:  {known_weight} kg")
    print(f"  Scale Factor:  {scale_factor:.10f} kg/unit")
    print('='*60)
    
    return zero_value, scale_factor

def main():
    print("="*60)
    print("LOAD CELL CALIBRATION HELPER")
    print("="*60)
    print("\nThis script will help you calibrate your load cells.")
    print("You will need:")
    print("  - A known weight (e.g., 1 kg, 5 kg, 10 kg)")
    print("  - The weight should be appropriate for your load cell range")
    print()
    
    # Initialize ADC
    print("Initializing ADS1256...")
    try:
        ads = ADS1256(cs_pin=CS_PIN, drdy_pin=DRDY_PIN)
        ads.set_data_rate(DRATE_100)
        ads.set_gain(GAIN_1)
        ads.calibrate()
        print("✓ ADS1256 initialized and calibrated")
    except Exception as e:
        print(f"✗ Failed to initialize ADS1256: {e}")
        print("  Check wiring and run test_ads1256.py first")
        return
    
    # Calibrate both channels
    zero1, scale1 = calibrate_channel(ads, CHANNEL_1, "Load Cell 1")
    zero2, scale2 = calibrate_channel(ads, CHANNEL_2, "Load Cell 2")
    
    # Generate code snippet
    print("\n" + "="*60)
    print("CALIBRATION COMPLETE!")
    print("="*60)
    print("\nAdd this code to your script:\n")
    print("# Calibration values (generated by calibrate_load_cells.py)")
    print(f"TARE_1 = {zero1:.2f}")
    print(f"TARE_2 = {zero2:.2f}")
    if scale1 is not None:
        print(f"SCALE_1 = {scale1:.10f}  # kg per unit")
    if scale2 is not None:
        print(f"SCALE_2 = {scale2:.10f}  # kg per unit")
    print("\n# Convert raw readings to weight:")
    print("weight_1_kg = (raw_value_1 - TARE_1) * SCALE_1")
    print("weight_2_kg = (raw_value_2 - TARE_2) * SCALE_2")
    print()
    
    # Test readings with calibration
    if scale1 is not None or scale2 is not None:
        print("="*60)
        test = input("\nWould you like to test the calibration? (y/n): ")
        if test.lower() == 'y':
            print("\nReading calibrated values (Ctrl+C to stop)...\n")
            try:
                while True:
                    r1 = ads.read_channel(CHANNEL_1)
                    r2 = ads.read_channel(CHANNEL_2)
                    
                    if r1 is not None and scale1 is not None:
                        w1 = (r1 - zero1) * scale1
                        print(f"LC1: {w1:8.3f} kg", end="   |   ")
                    else:
                        print(f"LC1: [not calibrated]", end="   |   ")
                    
                    if r2 is not None and scale2 is not None:
                        w2 = (r2 - zero2) * scale2
                        print(f"LC2: {w2:8.3f} kg")
                    else:
                        print(f"LC2: [not calibrated]")
                    
                    time.sleep(0.2)
            except KeyboardInterrupt:
                print("\n\nTest stopped.")
    
    # Cleanup
    ads.cleanup()
    print("\nCalibration session complete!")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nCalibration interrupted by user.")
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()
